services:
  - type: web
    name: whatsapp-openai-assistant
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn_config.py
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_ASSISTANT_ID
        sync: false
      - key: PORT
        value: 10000
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.10.8
      - key: PYTHONUNBUFFERED
        value: true
